name: pytest

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Run tests for Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.11"
          - "3.12"

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Berlin"
      #----------------------------------------------
      #       check-out repo
      #----------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      #----------------------------------------------
      #       install uv and setup python
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Setup Python ${{ matrix.python-version }} on ${{ matrix.os }}
        run: uv python install ${{ matrix.python-version }}

      #----------------------------------------------
      #           install your root project
      #----------------------------------------------
      - name: Install the project
        run: uv sync --all-extras --dev

      #----------------------------------------------
      #     run tests and genenrate summaries
      #----------------------------------------------
      - uses: pavelzw/pytest-action@v2
        with:
          emoji: true
          verbose: true
          job-summary: true
          click-to-expand: true
          custom-pytest: uv run pytest tests
          report-title: "Test Report for Python ${{ matrix.python-version }} on ${{ matrix.os }}"
